apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: it_one
      port: 9000
      host: clickhouse
      username: it_one
      tlsSkipVerify: false
    secureJsonData:
      password: it_one